title = "Pathogen Informatics and Modelling Group"
baseURL = "https://www.bacpop.org"
languageCode = "en-gb"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = "G-T91W04JTYS"
enableRobotsTXT = true

[module]
    [[module.imports]]
        disable = false
        ignoreConfig = false
        ignoreImports = false
        path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    text_color = ""
    author = ""
    favicon = "images/favicon.svg"
    site_logo = "images/bacpop_logo_3.svg"
    description = "Methods, software and models for analysing bacterial populations and genomes"
    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    recent_posts_number = 3
    googleAnalyticsNew = "G-T91W04JTYS"

    [[params.ananke_socials]]
    name = "github"
    url = "https://github.com/bacpop"
    label = "bacpop github"

    [[params.ananke_socials]]
    name = "youtube"
    url = "https://youtube.com/@bacpop"
    label = "Bacpop/ScientificProgramming YouTube channel"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
