title = "Pathogen Informatics and Modelling Group"
baseURL = "https://www.bacpop.org"
languageCode = "en-gb"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = "G-T91W04JTYS"
enableRobotsTXT = true

[module]
    [[module.imports]]
        disable = false
        ignoreConfig = false
        ignoreImports = false
        path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    text_color = ""
    author = ""
    favicon = "images/favicon.svg"
    site_logo = "images/bacpop_logo_3.svg"
    description = "Methods, software and models for analysing bacterial populations and genomes"
    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    googleAnalyticsNew = "G-T91W04JTYS"

    [params.ananke]
    show_recent_posts = true
    recent_posts_number = 3

    [params.ananke.social.follow]
    new_window_icon = true # show a little "opens in new window" icon next to the link
    networks = [
    "github",
    "bluesky",
    ]

    [params.ananke.social.github]
    username = "bacpop"

    [params.ananke.social.bluesky]
    username = "bacpop.org"
    profilelink = "https://bsky.app/profile/bacpop.org"

    [markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = false
        startLevel = 2
